debug: true
server:
  port: 8080
  servlet:
    context-path: /
spring:
  session:
    store-type: none
  aop:
    proxy-target-class: true
  mvc:
    throw-exception-if-no-handler-found: true
  freemarker:
    cache: false
jpipe:
  pool:
    core-size: -1
    max-size: 20
    keep-alive: 60000
    queue-size: 10